#!/usr/bin/env bash

DRY_RUN=0

for arg in "$@"
do
    if [[ "$arg" = "--dry" ]]; then
        DRY_RUN=1
        break
    fi
done

if [[ "$arg" = "--dry" ]]; then
    echo "Dry run..."
else
    echo "Actual run..."
fi

for pkg_dir in */; do
    pkg_name=${pkg_dir%/}
    if [[ -d ${pkg_name}/.config ]]; then
        echo "Not running abount ${pkg_name}, because already we have ${pkg_name}/.config/"
        continue
    fi

    if [[ "$DRY_RUN" = 1 ]]; then
        echo "[DRY RUN] Package: $pkg_name"
        echo "  mkdir -p \"${pkg_name}-temp/.config\""
        echo "  mv \"${pkg_name}\" \"${pkg_name}-temp/.config/\""
        echo "  mv \"${pkg_name}-temp\" \"$pkg_name\""
    else
        echo "Processing package: ${pkg_name}"
        mkdir -p "${pkg_name}-temp/.config"
        mv "$pkg_name" "${pkg_name}-temp/.config/"
        mv "${pkg_name}-temp" "${pkg_name}"
    fi
done
