#!/usr/bin/env bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

# PLUGIN_DIR="$CONFIG_DIR/plugins"
export XDG_CONFIG_HOME="$HOME/.config"
source "$XDG_CONFIG_HOME/sketchybar/environment"
source "$THEME_DIR/tokyonight"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker
bar=(
    blur_radius="$BAR_BLUR_RADIUS"
    border_color="$BAR_BORDER_COLOR"
    color="$BAR_COLOR"
    corner_radius="$BAR_CORNER_RADIUS"
    height="$BAR_HEIGHT"
    margin="$BAR_MARGIN"
    position="$BAR_POSITION"
    padding_left="$BAR_PADDING"
    padding_right="$BAR_PADDING"
    y_offset="$BAR_Y_OFFSET"
)
sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
default=(
  background.color="$BACKGROUND_COLOR"
  background.border_color="$BACKGROUND_BORDER_COLOR"
  background.corner_radius="$BACKGROUND_CORNER_RADIUS"
  background.height="$BACKGROUND_HEIGHT"
  icon.drawing=off
  icon.font="$ICON_FONT"
  label.align="$LABEL_ALIGN"
  label.font="$LABEL_FONT"
  label.color="$LABEL_COLOR"
  label.highlight_color="$LABEL_HIGHLIGHT_COLOR"
  label.y_offset="$LABEL_Y_OFFSET"
  label.padding_left="$LABEL_PADDING"
  label.padding_right="$LABEL_PADDING"
  y_offset="$Y_OFFSET"
)
sketchybar --default "${default[@]}"

# Left
source "$ITEM_DIR/aerospace"
source "$ITEM_DIR/spacer"
source "$ITEM_DIR/front_app"

# Right
source "$ITEM_DIR/clock"

# Automatically apply configuration changes
sketchbar --hotloaded on

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

# Initialize focused workspace
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)
