#!/usr/bin/env bash
# NOTE: Window management

# Focus Window
alt - x : yabai -m window --focus recent
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# Swap window
shift + alt - x : yabai -m window --swap recent
shift + alt - h : yabai -m window --swap west
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north 
shift + alt - l : yabai -m window --swap east 

# Window resizing
shift + ctrl - l : yabai -m window --resize left:-40:0 || yabai -m window --resize right:40:0
shift + ctrl - h : yabai -m window --resize left:40:0 || yabai -m window --resize right:-40:0
shift + ctrl - j : yabai -m window --resize top:0:40 || yabai -m window --resize bottom:0:-40
shift + ctrl - k : yabai -m window --resize top:0:-40 || yabai -m window --resize bottom:0:40

# Rotate Tree
shift + cmd - r : yabai -m space --rotate 90

# Toggle Full screen
shift + cmd - f : yabai -m window --toggle zoom-fullscreen

# NOTE: Application Handling
# 
# [Domain] Brave Browser
# [Action] Open
shift + ctrl - b : open "/Applications/Brave Browser.app/"
# [Action] Close
shift + cmd - b : osascript -e 'tell application "Brave Browser" to quit'

# [Domain] Google Chrome
# [Action] Open
shift + ctrl - g : open "/Applications/Google Chrome.app/"
# [Action] Close
shift + cmd - g : osascript 'tell application "Google Chrome" to quit'

# [Domain] WezTerm, my lovely tty
# [Action] Open
shift + ctrl - w : "wezterm"
# [Action] Close
shift + cmd - w : osascript -e 'tell application "WezTerm" to quit'

# [Domain] Slack
# [Action] Open
shift + ctrl - s : open "/Applications/Slack.app/"
# [Action] Close
shift + cmd - s : osascript -e 'tell application "Slack" to quit'

