#!/usr/bin/env bash

# Debugging option, Just in time
yabai -m config debug_output on

# Global settings
yabai -m config external_bar off
yabai -m config menubar_opacity 1.0
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autoraise
yabai -m config display_arrangement_order default
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_insertion_point focused
yabai -m config window_zoom_persist on
yabai -m config window_shadow on
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9
yabai -m config window_animation_duration 0.0
yabai -m config split_ratio 0.5
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# Space settings
yabai -m config layout bsp
yabai -m config split_type auto
yabai -m config top_padding 04
yabai -m config bottom_padding 04
yabai -m config left_padding 04
yabai -m config right_padding 04
yabai -m config auto_balance on 

echo "yabai configuration is loaded..."
