# I don't like default key bind
unbind C-b

# Basics
source-file ~/.config/tmux/configs/set.tmux
source-file ~/.config/tmux/configs/remap.tmux


source-file ~/.config/tmux/plugins/configs/tpm.tmux
source-file ~/.config/tmux/plugins/configs/rose-pine.tmux
source-file ~/.config/tmux/plugins/configs/tmux2k.tmux

# Run all plugins
run ~/.tmux/plugins/tpm/tpm
